# Generated by Django 2.2 on 2019-08-01 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=5)),
                ('user_email', models.CharField(max_length=30)),
                ('user_subject', models.CharField(max_length=30)),
                ('user_message', models.CharField(max_length=1000)),
            ],
        ),
    ]
