# Generated by Django 2.2 on 2019-08-10 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_contractus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractus',
            name='user_email',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='contractus',
            name='user_message',
            field=models.TextField(max_length=800),
        ),
    ]
